### ISSUE TITLE
Silabs based matter device is not commissioning with Google Home Playstore's app 

### ISSUE THREAD

**Issue by palak-android** [google-home/sample-app-for-matter-android#121]
Hello @pierredelisle, 

I am able to commissioning Silabs based WiFi matter device with this [sample-app-for-matter-android](https://github.com/google-home/sample-app-for-matter-android).

Unfortunately this Silabs based WiFi matter device is not commissioning with [Google Home playstore's application](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app&hl=en&gl=US&pli=1).

Is playstore's application is differently work or anything required?

Thank you,
Palakkumar Suhagia

**Comment by pierredelisle** [comment]
Would be happy to help figure out where the issue lies, but would need more details.
Could you provide details on where the commissioning is failing with the Google Home App, along with phone logs?
See https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM).

**Comment by palak-android** [comment]
Hello @pierredelisle,

I have captured logs for more details of this issue.

GHSAFM version: 1.4.1
Test device: Silabs EFR32MG24B 
Release version of firmware(Matter version): V1.1.0-1.1
Google Play Services version:
$ adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep -E '(policy|optional)_home'
        com.google.android.gms.optional_home [231312065] [23.13.12 (100400-0)] [Download:000000fc/dl-Home.optional_231312100400.apk] [download:/Home.optional/231312100400:Home.optional:231312100400]

Phone logs:
[Android-mobile_logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/11273100/Android-mobile_logs.txt)

VIdeo of Google Home application:
https://user-images.githubusercontent.com/38459626/233077840-916b9a11-fbb8-47ec-bfe9-7e9f7d5b80d7.mp4

Please let me know if you want more details.

Regards,
Palakkumar Suhagia

**Comment by pierredelisle** [comment]
Thanks for providing the logs and video (very useful!).
As you can see in your video at 02:18, commissioning fails with the following error message:
```
Not a Matter-certified device
This device can't be setup or controlled with Google
```

You can also see this error in the logs:

```
04-19 17:45:30.180  4923  4923 E SetupDeviceViewModel: Commissioning failed with state Attestation failure. [CONTEXT service_id=336 ]
```

I assume you are using a "test" device. The reason is simply that the Google Home Application will not allow you to commission devices that are not officially certified.

Note that GHSAFM makes it possible for you to commission such test devices, but only after you confirm that you still want to commission a device that is not officially certified. 

Hope this helps.

**Comment by palak-android** [comment]
Thank you for your time and this important information @pierredelisle pierredelisle

**Comment by pierredelisle** [comment]
BTW, if you create a project in the Google Home Developer Console, you will then be able to commission your test device with the Google Home App. See https://developers.home.google.com/matter/get-started for more details.
