### ISSUE TITLE
Matter devices not working if Mobile is in different network

### ISSUE THREAD

**Issue by sahityadubey** [google-home/sample-app-for-matter-android#144]
I would like to present a specific use case that I am currently facing with regards to controlling Matter accessories, specifically a Smart Bulb, using a Google Nest Hub and an Android app named TestApp developed with the Chiptool SDK.

The process I followed is as follows:

- Commissioned a Google Nest Hub in the Google Home app.
- Commissioned a Matter accessory (Smart Bulb) into the Google Home app.
- Developed an Android app named TestApp using the Chiptool SDK.
- Shared the Matter device with my TestApp using a QR code.
- Intended to control (Turn On/Off) the Matter accessory from the TestApp.

However, I have encountered an issue in the following scenario: When attempting to control the Matter accessory from the TestApp on a different network, specifically when the mobile device is connected to a network separate from the one where the Google Nest Hub and Matter accessory are connected, an error is thrown.

Given this situation, I am seeking guidance on whether there is a method to control Matter accessories from a different network. I would greatly appreciate your assistance in resolving this matter and enabling seamless control of the Matter accessory across different networks.

**Comment by varshilglide** [comment]
yes @sahityadubey, I am also getting the same issue that you face.

**Comment by sahityadubey** [comment]
@pierredelisle / @ jonsmirl  Can you please provide resolution here?

**Comment by jonsmirl** [comment]
MDNS is used by Matter for name resolution. MDNS is a non-routable LAN based protocol.  When your phone is on the local  subnet MDNS will work. You can use an app like this to see the Matter devices: https://play.google.com/store/apps/details?id=com.mdns_discovery.app&hl=en_US&gl=US  If you then leave the area and switch onto another subnet (like cellular) Matter will stop working. Look in the MDNS app and notice that you can't see the Matter devices anymore.

How does Google Home keep working? The trick is that it doesn't leave the subnet. That's why you need a Nest Display. The Nest Display stays in the house on the subnet where it can access the Matter devices. The display then establishes a socket up to to Google Cloud. When you use the Home app on your phone, that app talks to Google Cloud which then forwards your request down to the Nest Display. The Nest Display is on the correct subnet and can control the Matter devices.

So unless you want to rebuild all of that and have a local device like the Nest Display, just use Google Home for remote control and not your own app.

**Comment by pierredelisle** [comment]
Thanks Jon for the clear explanations!
@sahityadubey @varshilglide 
You may be interested in the [Google Home API Developer Preview Program: Device APIs and Structure APIs](https://docs.google.com/forms/d/e/1FAIpQLSeWeft-jJ8qgwDyDpKE6bwjUmX_0576NqQap_Qb70uvNjcssQ/viewform).

**Comment by sahityadubey** [comment]
> MDNS is used by Matter for name resolution. MDNS is a non-routable LAN based protocol. When your phone is on the local subnet MDNS will work. You can use an app like this to see the Matter devices: https://play.google.com/store/apps/details?id=com.mdns_discovery.app&hl=en_US&gl=US If you then leave the area and switch onto another subnet (like cellular) Matter will stop working. Look in the MDNS app and notice that you can't see the Matter devices anymore.
> 
> How does Google Home keep working? The trick is that it doesn't leave the subnet. That's why you need a Nest Display. The Nest Display stays in the house on the subnet where it can access the Matter devices. The display then establishes a socket up to to Google Cloud. When you use the Home app on your phone, that app talks to Google Cloud which then forwards your request down to the Nest Display. The Nest Display is on the correct subnet and can control the Matter devices.
> 
> So unless you want to rebuild all of that and have a local device like the Nest Display, just use Google Home for remote control and not your own app.

@jonsmirl 
In my case, I want to use this in my own app and in another subnet (like cellular)
Is there any way we can achieve this functionality,
Or do I have to wait for this API to get this feature?
[Google Home API Developer Preview Program: Device APIs and Structure APIs](https://docs.google.com/forms/d/e/1FAIpQLSeWeft-jJ8qgwDyDpKE6bwjUmX_0576NqQap_Qb70uvNjcssQ/viewform)

**Comment by pierredelisle** [comment]
@sahityadubey 
As Jon explained, Google relies on cloud services to support remote access to devices in its ecosystem, and a “Google Hub” is required to make this works. I doubt you’ll want to reinvent the wheel here with your own app, and the new APIs I referred to will make this remote access possible to devices that are onboarded on the Google ecosystem.

**Comment by sahityadubey** [comment]
Thank you for your response
@pierredelisle

**Comment by jonsmirl** [comment]
> @sahityadubey As Jon explained, Google relies on cloud services to support remote access to devices in its ecosystem, and a “Google Hub” is required to make this works. I doubt you’ll want to reinvent the wheel here with your own app, and the new APIs I referred to will make this remote access possible to devices that are onboarded on the Google ecosystem.

Google Home API Developer Preview Program: Device APIs and Structure APIs
That's the hard way to solve the problem, VPN is easier.

Instead of making a new API you could make a special VPN which proxies the Matter requests. Then no one's app has to change. Use a single API to turn the VPN on only for the vendor's app (not all apps on the phone). Build a MDNS proxy into the VPN piece. The VPN also inspect the packets and will only pass Matter protocol packets.

From Google's side, you verify that the vendor app is signed into the same Google Account as the Google Hub and that the vendor app is Play verified and has API access. If all that checks, open an app specific VPN between the app and the remote Google Hub. That VPN proxies the MDNS and filters so that only Matter traffic can pass. Note that this VPN is not useful unless you have the Matter fabric keys.  Without the fabric keys all of the packets will just get discarded.

As an added bonus use this approach in your own Google Home app. Then when the customer is inside their home the Google Home app will use direct Matter commands. Outside the house it will the VPN proxy.  This approach is future proof for changes in Matter since it doesn't decode and understand what the Matter packets are doing.

**Comment by varshilglide** [comment]
Thank You for your response
@jonsmirl @pierredelisle
